apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
    spec:
      containers:
      - name: hello-java
        image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/hello-java:latest
        ports:
        - containerPort: 8080